{% set name = "OpenRAFT" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WISDEM/RAFT/archive/v{{ version }}.tar.gz
    # Download the tar-ball and do: openssl sha256 file.tar.gz to update
  sha256: 1414b47e3ced94ec86bea815f38dd247c63d6c97b704f161feaffab64badc65a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - matplotlib-base
    - moorpy
    - numpy
    - openmdao
    - pyhams
    - python >={{ python_min }}
    - pyyaml
    - ruamel.yaml
    - scipy
    - wisdem

test:
  # Imports won't work without ORBIT  
  #imports:
  #  - raft
  requires:
    - pip
    - python {{ python_min }}
  source_files:
    - raft
    - examples
  commands:
    - pip install orbit-nrel
    - cd examples
    - python example_from_yaml.py false
    - cd ..

about:
  home: https://github.com/wisdem/raft
  summary: "RAFT: Response Amplitudes of Floating Turbines"
  description: |
    RAFT is a frequency domain analysis tool of floating offshore wind turbines
    that uses either strip theory or the HAMS boundary element method solver.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/wisdem/raft

extra:
  recipe-maintainers:
    - gbarter
    - mattEhall
